export const timezones = [
  { label: "Dateline Standard Time", value: "Dateline Standard Time" },
  { label: "UTC-11", value: "UTC-11" },
  { label: "Hawaiian Standard Time", value: "Hawaiian Standard Time" },
  { label: "Alaskan Standard Time", value: "Alaskan Standard Time" },
  {
    label: "Pacific Standard Time (Mexico)",
    value: "Pacific Standard Time (Mexico)",
  },
  { label: "Pacific Daylight Time", value: "Pacific Daylight Time" },
  { label: "Pacific Standard Time", value: "Pacific Standard Time" },
  { label: "US Mountain Standard Time", value: "US Mountain Standard Time" },
  {
    label: "Mountain Standard Time (Mexico)",
    value: "Mountain Standard Time (Mexico)",
  },
  { label: "Mountain Standard Time", value: "Mountain Standard Time" },
  {
    label: "Central America Standard Time",
    value: "Central America Standard Time",
  },
  { label: "Central Standard Time", value: "Central Standard Time" },
  {
    label: "Central Standard Time (Mexico)",
    value: "Central Standard Time (Mexico)",
  },
  {
    label: "Canada Central Standard Time",
    value: "Canada Central Standard Time",
  },
  { label: "SA Pacific Standard Time", value: "SA Pacific Standard Time" },
  { label: "Eastern Standard Time", value: "Eastern Standard Time" },
  { label: "Eastern Daylight Time", value: "Eastern Daylight Time" },
  { label: "US Eastern Standard Time", value: "US Eastern Standard Time" },
  { label: "Venezuela Standard Time", value: "Venezuela Standard Time" },
  { label: "Paraguay Standard Time", value: "Paraguay Standard Time" },
  { label: "Atlantic Standard Time", value: "Atlantic Standard Time" },
  {
    label: "Central Brazilian Standard Time",
    value: "Central Brazilian Standard Time",
  },
  { label: "SA Western Standard Time", value: "SA Western Standard Time" },
  { label: "Pacific SA Standard Time", value: "Pacific SA Standard Time" },
  { label: "Newfoundland Standard Time", value: "Newfoundland Standard Time" },
  {
    label: "E. South America Standard Time",
    value: "E. South America Standard Time",
  },
  { label: "Argentina Standard Time", value: "Argentina Standard Time" },
  { label: "SA Eastern Standard Time", value: "SA Eastern Standard Time" },
  { label: "Greenland Standard Time", value: "Greenland Standard Time" },
  { label: "Montevideo Standard Time", value: "Montevideo Standard Time" },
  { label: "Bahia Standard Time", value: "Bahia Standard Time" },
  { label: "UTC-02", value: "UTC-02" },
  { label: "Mid-Atlantic Standard Time", value: "Mid-Atlantic Standard Time" },
  { label: "Azores Standard Time", value: "Azores Standard Time" },
  { label: "Cape Verde Standard Time", value: "Cape Verde Standard Time" },
  { label: "Morocco Standard Time", value: "Morocco Standard Time" },
  { label: "UTC", value: "UTC" },
  { label: "GMT Standard Time", value: "GMT Standard Time" },
  { label: "British Summer Time", value: "British Summer Time" },
  { label: "GMT Standard Time", value: "GMT Standard Time" },
  { label: "Greenwich Standard Time", value: "Greenwich Standard Time" },
  { label: "W. Europe Standard Time", value: "W. Europe Standard Time" },
  {
    label: "Central Europe Standard Time",
    value: "Central Europe Standard Time",
  },
  { label: "Romance Standard Time", value: "Romance Standard Time" },
  {
    label: "Central European Standard Time",
    value: "Central European Standard Time",
  },
  {
    label: "W. Central Africa Standard Time",
    value: "W. Central Africa Standard Time",
  },
  { label: "Namibia Standard Time", value: "Namibia Standard Time" },
  { label: "GTB Standard Time", value: "GTB Standard Time" },
  { label: "Middle East Standard Time", value: "Middle East Standard Time" },
  { label: "Egypt Standard Time", value: "Egypt Standard Time" },
  { label: "Syria Standard Time", value: "Syria Standard Time" },
  { label: "E. Europe Standard Time", value: "E. Europe Standard Time" },
  { label: "South Africa Standard Time", value: "South Africa Standard Time" },
  { label: "FLE Standard Time", value: "FLE Standard Time" },
  { label: "Turkey Standard Time", value: "Turkey Standard Time" },
  { label: "Israel Standard Time", value: "Israel Standard Time" },
  { label: "Libya Standard Time", value: "Libya Standard Time" },
  { label: "Jordan Standard Time", value: "Jordan Standard Time" },
  { label: "Arabic Standard Time", value: "Arabic Standard Time" },
  { label: "Kaliningrad Standard Time", value: "Kaliningrad Standard Time" },
  { label: "Arab Standard Time", value: "Arab Standard Time" },
  { label: "E. Africa Standard Time", value: "E. Africa Standard Time" },
  { label: "Moscow Standard Time", value: "Moscow Standard Time" },
  { label: "Samara Time", value: "Samara Time" },
  { label: "Iran Standard Time", value: "Iran Standard Time" },
  { label: "Arabian Standard Time", value: "Arabian Standard Time" },
  { label: "Azerbaijan Standard Time", value: "Azerbaijan Standard Time" },
  { label: "Mauritius Standard Time", value: "Mauritius Standard Time" },
  { label: "Georgian Standard Time", value: "Georgian Standard Time" },
  { label: "Caucasus Standard Time", value: "Caucasus Standard Time" },
  { label: "Afghanistan Standard Time", value: "Afghanistan Standard Time" },
  { label: "West Asia Standard Time", value: "West Asia Standard Time" },
  { label: "Yekaterinburg Time", value: "Yekaterinburg Time" },
  { label: "Pakistan Standard Time", value: "Pakistan Standard Time" },
  { label: "India Standard Time", value: "India Standard Time" },
  { label: "Sri Lanka Standard Time", value: "Sri Lanka Standard Time" },
  { label: "Nepal Standard Time", value: "Nepal Standard Time" },
  { label: "Central Asia Standard Time", value: "Central Asia Standard Time" },
  { label: "Bangladesh Standard Time", value: "Bangladesh Standard Time" },
  { label: "Myanmar Standard Time", value: "Myanmar Standard Time" },
  { label: "SE Asia Standard Time", value: "SE Asia Standard Time" },
  {
    label: "N. Central Asia Standard Time",
    value: "N. Central Asia Standard Time",
  },
  { label: "China Standard Time", value: "China Standard Time" },
  { label: "North Asia Standard Time", value: "North Asia Standard Time" },
  { label: "Singapore Standard Time", value: "Singapore Standard Time" },
  { label: "W. Australia Standard Time", value: "W. Australia Standard Time" },
  { label: "Taipei Standard Time", value: "Taipei Standard Time" },
  { label: "Ulaanbaatar Standard Time", value: "Ulaanbaatar Standard Time" },
  {
    label: "North Asia East Standard Time",
    value: "North Asia East Standard Time",
  },
  { label: "Japan Standard Time", value: "Japan Standard Time" },
  { label: "Korea Standard Time", value: "Korea Standard Time" },
  {
    label: "Cen. Australia Standard Time",
    value: "Cen. Australia Standard Time",
  },
  { label: "AUS Central Standard Time", value: "AUS Central Standard Time" },
  { label: "E. Australia Standard Time", value: "E. Australia Standard Time" },
  { label: "AUS Eastern Standard Time", value: "AUS Eastern Standard Time" },
  { label: "West Pacific Standard Time", value: "West Pacific Standard Time" },
  { label: "Tasmania Standard Time", value: "Tasmania Standard Time" },
  { label: "Yakutsk Standard Time", value: "Yakutsk Standard Time" },
  {
    label: "Central Pacific Standard Time",
    value: "Central Pacific Standard Time",
  },
  { label: "Vladivostok Standard Time", value: "Vladivostok Standard Time" },
  { label: "New Zealand Standard Time", value: "New Zealand Standard Time" },
  { label: "UTC+12", value: "UTC+12" },
  { label: "Fiji Standard Time", value: "Fiji Standard Time" },
  { label: "Magadan Standard Time", value: "Magadan Standard Time" },
  { label: "Kamchatka Standard Time", value: "Kamchatka Standard Time" },
  { label: "Tonga Standard Time", value: "Tonga Standard Time" },
  { label: "Samoa Standard Time", value: "Samoa Standard Time" },
];
